const JOBS = [
    {
      title: 'React Js Developer',
      company: 'Uplers',
      location: 'India (Remote)',
      logoUrl: 'https://media.licdn.com/dms/image/C560BAQG6KMZp1zAiTA/company-logo_100_100/0/1578021573435?e=1700092800&v=beta&t=VQgH-gRrIviYOcsGq_QQCTOuJnSRYDPQ_ly_a-IR3Lw',
      postedTime: '3 hrs ago',
    },
    {
      title: 'Frontend Engineer',
      company: 'TechCorp',
      location: 'San Francisco, CA',
      logoUrl: 'https://media.licdn.com/dms/image/D4D0BAQHB79AE71th8A/company-logo_100_100/0/1688472201106?e=1701907200&v=beta&t=ZCYHGXDnO0Du7UXb-IHYfe3iWfG0FmKA3i0et44hFA0',
      postedTime: '5 hrs ago',
    },
    {
      title: 'UX/UI Designer',
      company: 'DesignHub',
      location: 'New York, NY',
      logoUrl: 'https://media.licdn.com/dms/image/C560BAQFd4vnxjnTdew/company-logo_100_100/0/1519885104638?e=1701907200&v=beta&t=FvMYa3wjquNw69IsdziZ-wcnGwGU99RMB0OSmJ73rAo',
      postedTime: '1 day ago',
    },
    {
      title: 'Software Engineer',
      company: 'CodeMasters',
      location: 'London, UK',
      logoUrl: 'https://media.licdn.com/dms/image/D4E0BAQFYKOlySeU0aw/company-logo_100_100/0/1688379914223?e=1701907200&v=beta&t=tDYEIzVKJUxASDCNhSTSTh0FUPwf1tEyREnyGB0jQoU',
      postedTime: '2 days ago',
    },
    {
      title: 'Data Scientist',
      company: 'Data Insights',
      location: 'Berlin, Germany',
      logoUrl: 'https://media.licdn.com/dms/image/C4D0BAQHPXS5u6n5KQA/company-logo_100_100/0/1519932890580?e=1701907200&v=beta&t=edFWsMQbQyfDFzPPd3iLlsZ3ElC5I4JRwahb6umBrnM',
      postedTime: '4 days ago',
    },
    {
      title: 'Product Manager',
      company: 'Tech Innovators',
      location: 'Los Angeles, CA',
      logoUrl: 'https://media.licdn.com/dms/image/C4E0BAQHmbrjmyoXhrA/company-logo_100_100/0/1555406537261?e=1701907200&v=beta&t=mi4m_NVSITzLrKOcXbSIxcbcuVsuPP4tyysL_XhvVxw',
      postedTime: '1 week ago',
    },
    {
      title: 'Full Stack Developer',
      company: 'DevPro',
      location: 'Chicago, IL',
      logoUrl: 'https://media.licdn.com/dms/image/C4E0BAQE5z0rD_Yq4Qg/company-logo_100_100/0/1671100540744?e=1701907200&v=beta&t=Fv4MjaodCcVcAoNFwwMsMO4JhP7ghQoV_9YDYatNu68',
      postedTime: '2 weeks ago',
    },
    {
      title: 'Marketing Manager',
      company: 'MarketMasters',
      location: 'Austin, TX',
      logoUrl: 'https://example.com/company-logo7.png',
      postedTime: '3 weeks ago',
    },
    {
      title: 'Data Analyst',
      company: 'Data Solutions',
      location: 'Toronto, Canada',
      logoUrl: 'https://example.com/company-logo8.png',
      postedTime: '1 month ago',
    },
    {
      title: 'UI Designer',
      company: 'Design Trends',
      location: 'Paris, France',
      logoUrl: 'https://example.com/company-logo9.png',
      postedTime: '2 months ago',
    },
    {
      title: 'Backend Developer',
      company: 'BackEndTech',
      location: 'Sydney, Australia',
      logoUrl: 'https://example.com/company-logo10.png',
      postedTime: '3 months ago',
    },
    {
      title: 'Content Writer',
      company: 'ContentCreators',
      location: 'Mumbai, India',
      logoUrl: 'https://example.com/company-logo11.png',
      postedTime: '4 months ago',
    },
    {
      title: 'QA Engineer',
      company: 'QualityTest',
      location: 'Singapore',
      logoUrl: 'https://example.com/company-logo12.png',
      postedTime: '5 months ago',
    },
    {
      title: 'Digital Marketing Specialist',
      company: 'DigitalStrategies',
      location: 'Dubai, UAE',
      logoUrl: 'https://example.com/company-logo13.png',
      postedTime: '6 months ago',
    },
    {
      title: 'DevOps Engineer',
      company: 'DevOps Solutions',
      location: 'Stockholm, Sweden',
      logoUrl: 'https://example.com/company-logo14.png',
      postedTime: '7 months ago',
    },
    {
      title: 'Business Analyst',
      company: 'Business Insights',
      location: 'Hong Kong',
      logoUrl: 'https://example.com/company-logo15.png',
      postedTime: '8 months ago',
    },
    {
      title: 'Sales Manager',
      company: 'Sales Pros',
      location: 'Barcelona, Spain',
      logoUrl: 'https://example.com/company-logo16.png',
      postedTime: '9 months ago',
    },
    {
      title: 'HR Coordinator',
      company: 'HR Connect',
      location: 'Sao Paulo, Brazil',
      logoUrl: 'https://example.com/company-logo17.png',
      postedTime: '10 months ago',
    },
    {
      title: 'Software Architect',
      company: 'Software Architects Inc.',
      location: 'Tokyo, Japan',
      logoUrl: 'https://example.com/company-logo18.png',
      postedTime: '11 months ago',
    },
    {
      title: 'Marketing Coordinator',
      company: 'Marketing Experts',
      location: 'Seoul, South Korea',
      logoUrl: 'https://example.com/company-logo19.png',
      postedTime: '12 months ago',
    },
    {
      title: 'AI/ML Engineer',
      company: 'AI Innovations',
      location: 'Beijing, China',
      logoUrl: 'https://example.com/company-logo20.png',
      postedTime: '13 months ago',
    },
  ];
  
  export default JOBS